# Running NestJS
FROM node:18

# Define work dir
WORKDIR /usr/src/app

# Copy project files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all the remaining code
COPY . .

# Exposing the default Nestjs port
EXPOSE 3000

# Default command
CMD ["npm", "run", "start:dev"]
