version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db_rural
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rural_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # remove host node_modules conflict
    working_dir: /usr/src/app
    command: npm run start:dev
    environment:
      - NODE_ENV=development

volumes:
  pgdata: {}
