version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db_rural
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rural_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_app_prod
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

volumes:
  pgdata: {}
